version: "3.2"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  discovery-service:
    build: ../discovery
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/discovery-service/config/config.json
    volumes:
      - ../discovery/config/consul-config.json:/discovery-service/config/config.json
      - ../discovery/data:/discovery-service/data
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5401:5432
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    restart: always

  user-service:
    build: ../services/user
    container_name: user-service
    ports:
      - 7001:7001
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    depends_on:
      - user-db
      - discovery-service
